=== madmilla/Distributed-Autonomous-Systems/10_start/WebContent/cd3.dtd
<!ELEMENT collectie (eigenaar,cd+)>
<!ELEMENT eigenaar (#PCDATA)>
<!ELEMENT cd (artiest,titel,jaar,uitgeleend?,lener?)>
<!ELEMENT artiest (#PCDATA)>
<!ELEMENT titel (#PCDATA)>
<!ELEMENT jaar (#PCDATA)>
<!ELEMENT uitgeleend (#PCDATA)>
<!ELEMENT lener (#PCDATA)>

=== madmilla/Distributed-Autonomous-Systems/10_start/WebContent/cd3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="cd3.xsl"?>
<!DOCTYPE collectie SYSTEM "cd3.dtd">

<collectie>
  <eigenaar>Piet</eigenaar>
  <cd>	
    <artiest>Henk</artiest>
	<titel>HELP</titel>
	<jaar>1990</jaar>
	<lener>Jan</lener>
  </cd>

  <cd>
	<artiest>Frits</artiest>
	<titel>Goodbye</titel>
	<jaar>2002</jaar>
	<uitgeleend>nee</uitgeleend>
  </cd>
</collectie>
